version: '3.1'
services:

  db:
    container_name: ${PROJECT}-mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ${PWD}
    volumes:
      - ${PWD}/data/mysql:/var/lib/mysql
      - ${PWD}:/var/www
    ports:
      - ${MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - bridge

  rabbitmq:
    container_name: ${PROJECT}-rabbitmq
    image: 'rabbitmq:3-management'
    hostname: ${RABBITMQ_HOST}
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_USER}
    labels:
      NAME: "rabbitmq"
    volumes:
      - ${PWD}:/var/www
    networks:
      - bridge

  memcache:
    container_name: ${PROJECT}-memcache
    image: memcached:latest
    restart: always
    networks:
      - bridge

  adminer:
    container_name: ${PROJECT}-adminer
    image: adminer:latest
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - bridge

  php-fpm:
    container_name: ${PROJECT}-php-fpm
    build: .docker/php-fpm/
    image: centos-php-fpm:7
    restart: always
    ports:
      - ${FPM_PORT}:1010
    environment:
      - APPLICATION_ENV=${APPLICATION_ENV}
      - ${PWD}
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - XDEBUG_CONFIG=remote_host=${XDEBUG_HOST} remote_port=${XDEBUG_PORT}
    volumes:
      - ${PWD}:/var/www
    networks:
      - bridge

  nginx:
    container_name: ${PROJECT}-nginx
    build: .docker/nginx/
    image: custom-nginx:latest
    restart: always
    depends_on:
      - php-fpm
    environment:
      - APPLICATION_ENV=${APPLICATION_ENV}
      - ${PWD}
      - ${PROJECT}
      - ${SITE_NAME}
      - ${FPM_HOST}
      - ${FPM_PORT}
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}:/var/www
    ports:
      - ${NGINX_PORT}:80
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
